Import freesurfer 5.3+cvs20130513
Signed-off-by: Mark Hymers <mark.hymers@ynic.york.ac.uk>

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2011/10/07 19:17:55 $
-#    $Revision: 1.49.2.1 $
+#    $Date: 2013/03/25 18:04:53 $
+#    $Revision: 1.49.2.3 $
 #
 # Copyright © 2011 The General Hospital Corporation (Boston, MA) "MGH"
 #
@@ -22,7 +22,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.49.2.1 2011/10/07 19:17:55 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.49.2.3 2013/03/25 18:04:53 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -32,6 +32,7 @@ set frame = ();
 set midframe = 0;
 set outreg = ();
 set outfsl = ();
+set outlta = ();
 set InitFSL = 0;
 set InitSPM = 0;
 set SPMUseNII = 0;
@@ -149,7 +150,7 @@ if($#InitReg == 0) then
   if($InitFSL) then
     set cmd = (fslregister --s $subject --mov $regvol --reg $InitReg \
       --niters 1 --maxangle 90 --nobetmov --tmp $tmpdir/fslregister \
-      --dof $FSLDOF --fsvol $fsvol)
+      --dof $FSLDOF --fsvol $fsvol.mgz)
     if($FSLSwapTrans) set cmd = ($cmd --allow-swap --trans)
     if($nolog) set cmd = ($cmd --nolog)
     echo $cmd | tee -a $LF
@@ -271,6 +272,14 @@ endif
 if($#outfsl) then
   set cmd = (tkregister2_cmdl --mov $movvol --reg $outreg \
     --noedit --fslregout $outfsl);
+  echo $cmd | tee -a $LF
+  $cmd | tee -a $LF
+  if($status) exit 1;
+endif
+
+if($#outlta) then
+  set cmd = (tkregister2_cmdl --mov $movvol --reg $outreg \
+    --noedit --ltaout $outlta);
   echo $cmd | tee -a $LF
   $cmd | tee -a $LF
   if($status) exit 1;
@@ -404,6 +413,11 @@ while( $#argv != 0 )
     case "--fslmat":
       if ( $#argv < 1) goto arg1err;
       set outfsl = $argv[1]; shift;
+      breaksw
+
+    case "--lta":
+      if ( $#argv < 1) goto arg1err;
+      set outlta = $argv[1]; shift;
       breaksw
 
     case "--init-fsl":
@@ -745,8 +759,12 @@ check_params:
   endif
 
   if($#outreg == 0) then
-    echo "ERROR: must spec an output reg file"
-    exit 1;
+    if ($#outlta == 0) then
+      echo "ERROR: must spec an output reg file (using either --reg or --lta)"
+      exit 1;
+    else
+      set outreg = ${outlta:r}.dat
+    endif
   endif
 
   if($#frame && $midframe) then
